name: t22e_cli
description: A terminal user interface framework.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.6

dependencies:
  protocol:
    path: ../../packages/protocol
  ansi:
    path: ../../packages/ansi
  unicode:
    path: ../../packages/unicode
  parser:
    path: ../../packages/parser
  core:
    path: ../../packages/core
  renderer:
    path: ../../packages/renderer
  capability:
    path: ../../packages/capability
  terminal:
    path: ../../packages/terminal
  lifecycle:
    path: ../../packages/lifecycle
  widgets:
    path: ../../packages/widgets

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  testing:
    path: ../../packages/testing
