import 'ansi/ansi_test.dart' as ansi;
import 'unicode/unicode_test.dart' as unicode;
import 'parser/events_test.dart' as events;
import 'parser/engine_test.dart' as engine;
import 'parser/csi_parser_test.dart' as csi;
import 'parser/esc_parser_test.dart' as esc;
import 'parser/osc_parser_test.dart' as osc;
import 'parser/dcs_parser_test.dart' as dcs;
import 'parser/parser_test.dart' as parser;
import 'terminal/terminal_test.dart' as terminal;
import 'core/geometry_test.dart' as geometry;
import 'core/color_test.dart' as color;
import 'core/cell_test.dart' as cell;
import 'core/style_test.dart' as style;
import 'core/surface_test.dart' as surface;
import 'core/layout_test.dart' as layout;
import 'renderer/frame_test.dart' as frame;
import 'renderer/line_renderer_test.dart' as lineRenderer;
import 'renderer/sync_renderer_test.dart' as syncRenderer;
import 'widgets/basic/spacer_test.dart' as spacer;
import 'widgets/basic/text_test.dart' as text;
import 'widgets/basic/box_test.dart' as box;
import 'widgets/container/row_test.dart' as row;
import 'widgets/container/column_test.dart' as column;
import 'widgets/renderer_test.dart' as widgetRenderer;
import 'widgets/visual/progress_test.dart' as progress;
import 'widgets/visual/spinner_test.dart' as spinner;
import 'widgets/visual/table_test.dart' as table;
import 'widgets/visual/dialog_test.dart' as dialog;
import 'widgets/interactive/list_test.dart' as listView;
import 'widgets/interactive/text_input_test.dart' as textInput;
import 'widgets/basic/link_test.dart' as link;
import 'renderer/cell_renderer_test.dart' as cellRenderer;
import 'renderer/benchmark_test.dart' as benchmark;
import 'testing/virtual_terminal_test.dart' as virtualTerminal;
import 'testing/widget_tester_test.dart' as widgetTester;

void main() {
  ansi.main();
  unicode.main();
  events.main();
  engine.main();
  csi.main();
  esc.main();
  osc.main();
  dcs.main();
  parser.main();
  terminal.main();
  geometry.main();
  color.main();
  cell.main();
  style.main();
  surface.main();
  layout.main();
  frame.main();
  lineRenderer.main();
  syncRenderer.main();
  spacer.main();
  text.main();
  box.main();
  row.main();
  column.main();
  widgetRenderer.main();
  progress.main();
  spinner.main();
  table.main();
  dialog.main();
  listView.main();
  textInput.main();
  link.main();
  cellRenderer.main();
  benchmark.main();
  virtualTerminal.main();
  widgetTester.main();
}
