name: CI

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: "3.12.0"

      - uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: true

      - name: Analyze
        run: melos analyze

      - name: Test
        run: melos test

      - name: Format
        run: melos format
